// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu8MNUT4VXz0Hyx3ZpkviUeserxvnIMns',
    appId: '1:435100924849:web:6d0af4963efc7191291b90',
    messagingSenderId: '435100924849',
    projectId: 'simplevehicle-896c0',
    authDomain: 'simplevehicle-896c0.firebaseapp.com',
    storageBucket: 'simplevehicle-896c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBunKNZnQxQfsq8kRsgBgtkAml8Fd0z3pE',
    appId: '1:435100924849:android:f82af8078126231c291b90',
    messagingSenderId: '435100924849',
    projectId: 'simplevehicle-896c0',
    storageBucket: 'simplevehicle-896c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZtVZiv1szYClBxazpJy49apPb6EUor0',
    appId: '1:435100924849:ios:0a3223aea7071f4b291b90',
    messagingSenderId: '435100924849',
    projectId: 'simplevehicle-896c0',
    storageBucket: 'simplevehicle-896c0.firebasestorage.app',
    iosBundleId: 'com.example.simpleVehicleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZtVZiv1szYClBxazpJy49apPb6EUor0',
    appId: '1:435100924849:ios:0a3223aea7071f4b291b90',
    messagingSenderId: '435100924849',
    projectId: 'simplevehicle-896c0',
    storageBucket: 'simplevehicle-896c0.firebasestorage.app',
    iosBundleId: 'com.example.simpleVehicleApp',
  );
}
