// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWYk5d8h7fdMIXMxNruEiqeyY3Q7ooydk',
    appId: '1:69347039922:web:08c9cb89d6b538b73987ab',
    messagingSenderId: '69347039922',
    projectId: 'exam-collector-app',
    authDomain: 'exam-collector-app.firebaseapp.com',
    storageBucket: 'exam-collector-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvqHBLbvy6jqrkiIF6rxtLn8wqV4v0SLY',
    appId: '1:69347039922:android:000fe339c7e398a83987ab',
    messagingSenderId: '69347039922',
    projectId: 'exam-collector-app',
    storageBucket: 'exam-collector-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB81uaXqbq6Pzrc2N5p594rN89H1xzHAc',
    appId: '1:69347039922:ios:c3e3880f8c5331393987ab',
    messagingSenderId: '69347039922',
    projectId: 'exam-collector-app',
    storageBucket: 'exam-collector-app.appspot.com',
    iosBundleId: 'com.ExamCollectorAdminApp.examCollectorAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB81uaXqbq6Pzrc2N5p594rN89H1xzHAc',
    appId: '1:69347039922:ios:c3e3880f8c5331393987ab',
    messagingSenderId: '69347039922',
    projectId: 'exam-collector-app',
    storageBucket: 'exam-collector-app.appspot.com',
    iosBundleId: 'com.ExamCollectorAdminApp.examCollectorAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWYk5d8h7fdMIXMxNruEiqeyY3Q7ooydk',
    appId: '1:69347039922:web:8d226d7b42053f8b3987ab',
    messagingSenderId: '69347039922',
    projectId: 'exam-collector-app',
    authDomain: 'exam-collector-app.firebaseapp.com',
    storageBucket: 'exam-collector-app.appspot.com',
  );
}
